old_templates = [
    lambda c: f'{c}的照片。',
    lambda c: f'质量差的{c}的照片。',
    lambda c: f'许多{c}的照片。',
    lambda c: f'{c}的雕塑。',
    lambda c: f'难以看到{c}的照片。',
    lambda c: f'{c}的低分辨率照片。',
    lambda c: f'{c}的渲染。',
    lambda c: f'涂鸦{c}。',
    lambda c: f'{c}的糟糕照片。',
    lambda c: f'{c}的裁剪照片。',
    lambda c: f'{c}的纹身。',
    lambda c: f'{c}的刺绣照片。',
    lambda c: f'很难看到{c}的照片。',
    lambda c: f'{c}的明亮照片。',
    lambda c: f'一张干净的{c}的照片。',
    lambda c: f'一张包含{c}的照片。',
    lambda c: f'{c}的深色照片。',
    lambda c: f'{c}的手绘画。',
    lambda c: f'我的{c}的照片。',
    lambda c: f'不自然的{c}的照片。',
    lambda c: f'一张酷的{c}的照片。',
    lambda c: f'{c}的特写照片。',
    lambda c: f'{c}的黑白照片。',
    lambda c: f'一幅{c}的画。',
    lambda c: f'一幅{c}的绘画。',
    lambda c: f'一张{c}的像素照片。',
    lambda c: f'{c}的雕像。',
    lambda c: f'一张{c}的明亮照片。',
    lambda c: f'{c}的裁剪照片。',
    lambda c: f'人造的{c}的照片。',
    lambda c: f'一张关于{c}的照片。',
    lambda c: f'损坏的{c}的jpeg照片。',
    lambda c: f'{c}的模糊照片。',
    lambda c: f'{c}的相片。',
    lambda c: f'一张{c}的好照片。',
    lambda c: f'{c}的渲染照。',
    lambda c: f'视频游戏中的{c}。',
    lambda c: f'一张{c}的照片。',
    lambda c: f'{c}的涂鸦。',
    lambda c: f'{c}的近距离照片。',
    lambda c: f'{c}的折纸。',
    lambda c: f'{c}在视频游戏中。',
    lambda c: f'{c}的草图。',
    lambda c: f'{c}的涂鸦照。',
    lambda c: f'{c}的折纸形状。',
    lambda c: f'低分辨率的{c}的照片。',
    lambda c: f'玩具{c}。',
    lambda c: f'{c}的副本。',
    lambda c: f'{c}的干净的照片。',
    lambda c: f'一张大{c}的照片。',
    lambda c: f'{c}的重现。',
    lambda c: f'一张漂亮的{c}的照片。',
    lambda c: f'一张奇怪的{c}的照片。',
    lambda c: f'模糊的{c}的照片。',
    lambda c: f'卡通{c}。',
    lambda c: f'{c}的艺术作品。',
    lambda c: f'{c}的素描。',
    lambda c: f'刺绣{c}。',
    lambda c: f'{c}的像素照。',
    lambda c: f'{c}的拍照。',
    lambda c: f'{c}的损坏的照片。',
    lambda c: f'高质量的{c}的照片。',
    lambda c: f'毛绒玩具{c}。',
    lambda c: f'漂亮的{c}的照片。',
    lambda c: f'小{c}的照片。',
    lambda c: f'照片是奇怪的{c}。',
    lambda c: f'漫画{c}。',
    lambda c: f'{c}的艺术照。',
    lambda c: f'{c}的图形。',
    lambda c: f'大{c}的照片。',
    lambda c: f'黑白的{c}的照片。',
    lambda c: f'{c}毛绒玩具。',
    lambda c: f'一张{c}的深色照片。',
    lambda c: f'{c}的摄影图。',
    lambda c: f'{c}的涂鸦照。',
    lambda c: f'玩具形状的{c}。',
    lambda c: f'拍了{c}的照片。',
    lambda c: f'酷酷的{c}的照片。',
    lambda c: f'照片里的小{c}。',
    lambda c: f'{c}的刺青。',
]


fruit_template = [
    lambda f: f'一颗新鲜的{f}。',
    lambda f: f'一个{f}水果。',
    lambda f: f'一种名为{f}的水果。',
    lambda f: f'这是一张{f}的照片。',
    lambda f: f'{f}水果的外观展示。',
    lambda f: f'一份{f}。',
    lambda f: f'展示{f}水果的图片。',
    lambda f: f'一种口感鲜美的{f}。',
    lambda f: f'一张{f}的展示照片。',
    lambda f: f'品尝{f}水果的照片。',
    lambda f: f'{f}水果的特写照。',
    lambda f: f'一份新鲜的{f}水果。',
    lambda f: f'这是{f}的水果图片。',
    lambda f: f'{f}水果的品种展示。',
    lambda f: f'一张名为{f}的水果照片。',
    lambda f: f'品尝新鲜的{f}。',
    lambda f: f'一颗成熟的{f}水果。',
    lambda f: f'一种多汁的{f}。',
    lambda f: f'一张展示{f}水果的照片。',
    lambda f: f'一份精选的{f}。',
]

furniture_template = [
    lambda f: f'一件名为{f}的家具。',
    lambda f: f'这是{f}家具的照片。',
    lambda f: f'一张展示{f}家具的图片。',
    lambda f: f'一套{f}家具。',
    lambda f: f'{f}家具的外观展示。',
    lambda f: f'一张{f}的照片。',
    lambda f: f'一件{f}家具。',
    lambda f: f'这是一款{f}。',
    lambda f: f'展示{f}家具的照片。',
    lambda f: f'一套名为{f}的家具。',
    lambda f: f'{f}家具的设计展示。',
    lambda f: f'一张{f}家具的外观照片。',
    lambda f: f'这是{f}的家具图片。',
    lambda f: f'{f}家具的风格展示。',
    lambda f: f'一款{f}家具的照片。',
    lambda f: f'一张显示{f}家具的照片。',
    lambda f: f'{f}家具的室内展示。',
    lambda f: f'一张{f}家具的设计照片。',
    lambda f: f'一套风格独特的{f}家具。',
    lambda f: f'欣赏{f}家具的照片。',
]


electronics_template = [
    lambda e: f'一款名为{e}的电子设备。',
    lambda e: f'这是{e}的照片。',
    lambda e: f'一张展示{e}的图片。',
    lambda e: f'一台{e}电子设备。',
    lambda e: f'{e}的外观展示。',
    lambda e: f'一张{e}的照片。',
    lambda e: f'一款{e}。',
    lambda e: f'这是一种{e}。',
    lambda e: f'展示{e}的照片。',
    lambda e: f'一台名为{e}的设备。',
    lambda e: f'{e}的功能展示。',
    lambda e: f'一张{e}的外观照片。',
    lambda e: f'这是{e}的设备图片。',
    lambda e: f'{e}的特点展示。',
    lambda e: f'一款{e}的照片。',
    lambda e: f'一张显示{e}的照片。',
    lambda e: f'{e}的用途展示。',
    lambda e: f'一张{e}的细节照片。',
    lambda e: f'一台外观独特的{e}设备。',
    lambda e: f'购买{e}的照片。',
]

food_template = [
    lambda f: f'一道名为{f}的食物。',
    lambda f: f'这是{f}食物的照片。',
    lambda f: f'一张展示{f}食物的图片。',
    lambda f: f'一份{f}。',
    lambda f: f'{f}食物的外观展示。',
    lambda f: f'一张{f}的照片。',
    lambda f: f'一道{f}食物。',
    lambda f: f'这是一种{f}。',
    lambda f: f'欣赏{f}食物的照片。',
    lambda f: f'一份名为{f}的食物。',
    lambda f: f'{f}食物的制作过程展示。',
    lambda f: f'一张{f}食物的外观照片。',
    lambda f: f'这是{f}的食物图片。',
    lambda f: f'{f}食物的特色展示。',
    lambda f: f'一道精致的{f}食物。',
    lambda f: f'一张显示{f}食物的照片。',
    lambda f: f'品尝美味的{f}。',
    lambda f: f'一张{f}食物的实际呈现照片。',
    lambda f: f'一道口感独特的{f}食物。',
    lambda f: f'欣赏{f}食物的照片。',
]

shoe_template = [
    lambda s: f'一双名为{s}的鞋子。',
    lambda s: f'这是{s}鞋子的照片。',
    lambda s: f'一张展示{s}鞋子的图片。',
    lambda s: f'一双{s}鞋。',
    lambda s: f'{s}鞋子的外观展示。',
    lambda s: f'一张{s}的照片。',
    lambda s: f'一双{s}鞋子。',
    lambda s: f'这是一款{s}。',
    lambda s: f'欣赏{s}鞋子的照片。',
    lambda s: f'一双名为{s}的鞋子。',
    lambda s: f'{s}鞋子的设计展示。',
    lambda s: f'一张{s}鞋子的外观照片。',
    lambda s: f'这是{s}的鞋子图片。',
    lambda s: f'{s}鞋子的特点展示。',
    lambda s: f'一款{s}鞋子的照片。',
    lambda s: f'一张显示{s}鞋子的照片。',
    lambda s: f'穿上舒适的{s}。',
    lambda s: f'一张{s}鞋子的实际穿着照片。',
    lambda s: f'一双时尚的{s}鞋子。',
    lambda s: f'欣赏{s}鞋子的照片。',
]

clothing_template = [
    lambda c: f'这是一件{c}。',
    lambda c: f'一张展示{c}的服装照片。',
    lambda c: f'一件名为{c}的衣服。',
    lambda c: f'这是{c}的样式展示。',
    lambda c: f'一张{c}衣服的照片。',
    lambda c: f'这是一款{c}。',
    lambda c: f'{c}的设计风格展示。',
    lambda c: f'一张{c}的外观照片。',
    lambda c: f'穿上漂亮的{c}。',
    lambda c: f'一张实际穿着{c}的照片。',
    lambda c: f'一件时尚的{c}。',
    lambda c: f'欣赏{c}的照片。',
    lambda c: f'这是一件名为{c}的衣物。',
    lambda c: f'{c}的特点展示。',
    lambda c: f'一款{c}的照片。',
    lambda c: f'一张显示{c}衣服的照片。',
    lambda c: f'这件衣服是{c}风格的。',
    lambda c: f'一张{c}衣服的实际穿着照片。',
    lambda c: f'一件舒适的{c}。',
    lambda c: f'一张{c}服装的照片。',
]+ [
    lambda c: f'一件时尚的{c}。',
    lambda c: f'这是一款{c}。',
    lambda c: f'穿上这件{c}，展现你的个性。',
    lambda c: f'一张{c}衣物的风格展示照片。',
    lambda c: f'这是一款名为{c}的时尚衣服。',
    lambda c: f'欣赏{c}的时尚照片。',
    lambda c: f'一件{c}，让你与众不同。',
    lambda c: f'一张展示{c}衣物的时尚照片。',
    lambda c: f'这是一件{c}，适合各种场合。',
    lambda c: f'一款{c}，让你更加自信。',
    lambda c: f'一张{c}衣物的穿着效果照片。',
    lambda c: f'这是一件名为{c}的潮流衣服。',
    lambda c: f'{c}的特色展示。',
    lambda c: f'一款{c}，展现你的时尚品味。',
    lambda c: f'一张显示{c}衣物的时尚照片。',
    lambda c: f'这件衣服是{c}的风格。',
    lambda c: f'一张{c}衣物的实际穿着效果照片。',
    lambda c: f'一件舒适又时尚的{c}。',
    lambda c: f'一张{c}服装的时尚照片。',
    lambda c: f'这是一款适合各种场合的{c}。',
    lambda c: f'{c}的设计理念展示。',
    lambda c: f'一件{c}，展现你的个性风格。',
    lambda c: f'欣赏{c}的设计理念照片。',
    lambda c: f'一张{c}衣物的设计理念照片。',
    lambda c: f'这是一件名为{c}的潮流时装。',
    lambda c: f'{c}的特点介绍。',
]


product_template = [
    lambda c: f'商品{c}的照片。',
    lambda c: f'一件{c}商品。',
    lambda c: f'一张{c}商品的照片。',
    lambda c: f'这是{c}的图片。',
    lambda c: f'{c}这个商品的照片。',
    lambda c: f'展示{c}商品的照片。',
    lambda c: f'一件名为{c}的商品。',
    lambda c: f'显示{c}商品的照片。',
    lambda c: f'一张展示{c}商品的照片。',
    lambda c: f'购买{c}商品的图片。',
    lambda c: f'{c}商品的外观展示。',
    lambda c: f'一款{c}商品的照片。',
    lambda c: f'这是{c}的外观图。',
    lambda c: f'{c}商品的展示照片。',
    lambda c: f'{c}商品的特写照片。',
    lambda c: f'一张{c}商品的外观照片。',
    lambda c: f'一款名为{c}的商品。',
    lambda c: f'查看{c}商品的照片。',
    lambda c: f'一张{c}的展示照片。',
    lambda c: f'{c}商品的正面照。',
    lambda c: f'一张展示{c}商品外观的照片。',
    lambda c: f'这是{c}的官方图片。',
    lambda c: f'{c}商品的细节照片。',
    lambda c: f'一张{c}商品的正面照片。',
    lambda c: f'一款外观为{c}的商品。',
    lambda c: f'欣赏{c}商品的照片。',
    lambda c: f'一张{c}商品的细节照片。',
    lambda c: f'{c}商品的展示图片。',
    lambda c: f'一件外观独特的{c}商品。',
]+ [
    lambda c: f'这是一张{c}商品的照片。',
    lambda c: f'一款{c}的展示图片。',
    lambda c: f'这是{c}商品的正面展示。',
    lambda c: f'{c}商品的特点展示。',
    lambda c: f'一张展示{c}商品特点的照片。',
    lambda c: f'这是{c}的官方外观图。',
    lambda c: f'{c}商品的俯视照片。',
    lambda c: f'一款名为{c}的独特商品。',
    lambda c: f'欣赏{c}商品的外观照片。',
    lambda c: f'一张{c}的俯视照片。',
    lambda c: f'{c}商品的材质展示。',
    lambda c: f'一张展示{c}商品材质的照片。',
    lambda c: f'这是{c}的官方展示图。',
    lambda c: f'{c}商品的背面照片。',
    lambda c: f'一款外观独特的{c}商品。',
    lambda c: f'查看{c}商品的外观照片。',
    lambda c: f'一张{c}商品的背面照片。',
    lambda c: f'{c}商品的设计展示。',
    lambda c: f'一张展示{c}商品设计的照片。',
    lambda c: f'这是{c}的官方设计图。',
    lambda c: f'{c}商品的侧面照片。',
    lambda c: f'一款名为{c}的创新商品。',
    lambda c: f'欣赏{c}商品的设计照片。',
    lambda c: f'一张{c}的侧面照片。',
    lambda c: f'{c}商品的功能展示。',
    lambda c: f'一张展示{c}商品功能的照片。',
    lambda c: f'这是{c}的官方功能图。',
    lambda c: f'{c}商品的包装照片。',
    lambda c: f'一款外观精美的{c}商品。',
    lambda c: f'查看{c}商品的功能照片。',
    lambda c: f'一张{c}商品的包装照片。',
]

clip_template = [
    lambda c: f'这是一张展示{c}的照片。',
    lambda c: f'一款展示{c}的图片。',
    lambda c: f'这是{c}的正面展示。',
    lambda c: f'{c}的特点展示。',
    lambda c: f'一张展示{c}特点的照片。',
    lambda c: f'这是{c}的官方外观图。',
    lambda c: f'{c}的俯视照片。',
    lambda c: f'欣赏这张展示{c}外观的照片。',
    lambda c: f'这张照片展现了{c}的魅力。',
    lambda c: f'一张关于{c}的视觉呈现。',
    lambda c: f'这是一张展示{c}的照片作品。',
    lambda c: f'这张照片展示了{c}的独特之处。',
    lambda c: f'一幅描绘{c}的画作。',
    lambda c: f'这是{c}的高清图片。',
    lambda c: f'在这张照片中可以看到{c}的细节。',
    lambda c: f'一张展示{c}风格的图片。',
    lambda c: f'这是一张展示{c}的摄影作品。',
    lambda c: f'这张照片展现了{c}的鲜艳色彩。',
    lambda c: f'这张照片捕捉到了{c}的瞬间。',
    lambda c: f'一张生动展示{c}的图像。',
    lambda c: f'这是一张展示{c}的绝佳照片。',
    lambda c: f'这张照片呈现了{c}的艺术之美。',
    lambda c: f'这张照片展示了{c}的美丽景色。',
    lambda c: f'一张展示{c}特色的摄影作品。',
    lambda c: f'这是{c}的概念艺术照。',
    lambda c: f'这张照片展示了{c}的独特韵味。',
    lambda c: f'一幅生动描绘{c}的图画。',
    lambda c: f'这是一张展示{c}的精致照片。',
    lambda c: f'这张照片展现了{c}的绚丽色彩。',
    lambda c: f'这张照片捕捉到了{c}的奇妙瞬间。',
    lambda c: f'一张生动展示{c}的视觉艺术。',
    lambda c: f'这是一张展示{c}的精美照片。',
    lambda c: f'这张照片呈现了{c}的独特光芒。',
    lambda c: f'一张令人惊叹的{c}画作。',
    lambda c: f'这是一张展示{c}的高清图片。',
    lambda c: f'这张照片展示了{c}的细腻之美。',
    lambda c: f'一张展示{c}风格的精彩摄影作品。',
]

imagenet_templates = [
    lambda c: f'a bad photo of a {c}.',
    lambda c: f'a photo of many {c}.',
    lambda c: f'a sculpture of a {c}.',
    lambda c: f'a photo of the hard to see {c}.',
    lambda c: f'a low resolution photo of the {c}.',
    lambda c: f'a rendering of a {c}.',
    lambda c: f'graffiti of a {c}.',
    lambda c: f'a bad photo of the {c}.',
    lambda c: f'a cropped photo of the {c}.',
    lambda c: f'a tattoo of a {c}.',
    lambda c: f'the embroidered {c}.',
    lambda c: f'a photo of a hard to see {c}.',
    lambda c: f'a bright photo of a {c}.',
    lambda c: f'a photo of a clean {c}.',
    lambda c: f'a photo of a dirty {c}.',
    lambda c: f'a dark photo of the {c}.',
    lambda c: f'a drawing of a {c}.',
    lambda c: f'a photo of my {c}.',
    lambda c: f'the plastic {c}.',
    lambda c: f'a photo of the cool {c}.',
    lambda c: f'a close-up photo of a {c}.',
    lambda c: f'a black and white photo of the {c}.',
    lambda c: f'a painting of the {c}.',
    lambda c: f'a painting of a {c}.',
    lambda c: f'a pixelated photo of the {c}.',
    lambda c: f'a sculpture of the {c}.',
    lambda c: f'a bright photo of the {c}.',
    lambda c: f'a cropped photo of a {c}.',
    lambda c: f'a plastic {c}.',
    lambda c: f'a photo of the dirty {c}.',
    lambda c: f'a jpeg corrupted photo of a {c}.',
    lambda c: f'a blurry photo of the {c}.',
    lambda c: f'a photo of the {c}.',
    lambda c: f'a good photo of the {c}.',
    lambda c: f'a rendering of the {c}.',
    lambda c: f'a {c} in a video game.',
    lambda c: f'a photo of one {c}.',
    lambda c: f'a doodle of a {c}.',
    lambda c: f'a close-up photo of the {c}.',
    lambda c: f'a photo of a {c}.',
    lambda c: f'the origami {c}.',
    lambda c: f'the {c} in a video game.',
    lambda c: f'a sketch of a {c}.',
    lambda c: f'a doodle of the {c}.',
    lambda c: f'a origami {c}.',
    lambda c: f'a low resolution photo of a {c}.',
    lambda c: f'the toy {c}.',
    lambda c: f'a rendition of the {c}.',
    lambda c: f'a photo of the clean {c}.',
    lambda c: f'a photo of a large {c}.',
    lambda c: f'a rendition of a {c}.',
    lambda c: f'a photo of a nice {c}.',
    lambda c: f'a photo of a weird {c}.',
    lambda c: f'a blurry photo of a {c}.',
    lambda c: f'a cartoon {c}.',
    lambda c: f'art of a {c}.',
    lambda c: f'a sketch of the {c}.',
    lambda c: f'a embroidered {c}.',
    lambda c: f'a pixelated photo of a {c}.',
    lambda c: f'itap of the {c}.',
    lambda c: f'a jpeg corrupted photo of the {c}.',
    lambda c: f'a good photo of a {c}.',
    lambda c: f'a plushie {c}.',
    lambda c: f'a photo of the nice {c}.',
    lambda c: f'a photo of the small {c}.',
    lambda c: f'a photo of the weird {c}.',
    lambda c: f'the cartoon {c}.',
    lambda c: f'art of the {c}.',
    lambda c: f'a drawing of the {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a black and white photo of a {c}.',
    lambda c: f'the plushie {c}.',
    lambda c: f'a dark photo of a {c}.',
    lambda c: f'itap of a {c}.',
    lambda c: f'graffiti of the {c}.',
    lambda c: f'a toy {c}.',
    lambda c: f'itap of my {c}.',
    lambda c: f'a photo of a cool {c}.',
    lambda c: f'a photo of a small {c}.',
    lambda c: f'a tattoo of the {c}.',
]

templates = product_template